Adding SQL functionality with Python for STUDENT tables
eugene-okulik/Lysaya pull request #16
Opened 2024-05-30 17:33 UTC by LysayaNatasha

2024-05-30 17:34 UTC, LysayaNatasha commented
Ну сейчас вроде правильно сделала

2024-05-31 10:39 UTC, eugene-okulik requested changes
Ваще круто всё, но нужно всегда оценивать насколько уникален тот запрос, который вытаскивает айдишки. Ведь мы хотим использовать айди именно тех данных, которые нам нужны, а не каких-то левых. И вот поиск по названию здесь - это не уникально.

2024-05-31 10:39 UTC, eugene-okulik commented on homework/natasha_lysaya/Homework_15_Lysaya/Homework_Lesson_15.py
> +student_id = cursor.lastrowid
Можно так, а можно и вообще не заполнять group_id - оно само выставится в NULL

2024-05-31 10:39 UTC, eugene-okulik commented on homework/natasha_lysaya/Homework_15_Lysaya/Homework_Lesson_15.py
> +]
Выглядит круто, но на приктике - плохо. В базе могут быть занятия с одинаковыми названиями. В строчке 64 ты создаешь словарь. В словаре все ключи уникальны. Какой айди сохранится под нужными названиями - не угадать.  
Короче, нужно при инсерте получать айдишки этих занятий. executemany не умеет возвращать все вставленные айдишки, поэтому, удобнее вставлять данные циклом.

2024-05-31 16:31 UTC, LysayaNatasha commented
Сейчас вроде ОК, а то в первом в фикс комите лишние строки разкоментила и не удалила, а оно все равно отработало)))) Только тут по  строкам разница комитов заметила

2024-06-02 12:21 UTC, eugene-okulik approved these changes

2024-06-02 12:21 UTC, merged